spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xingmeichen/helper
          searchPaths: spring_cloud_in_action/config-repo
          username: xingmeichen
          password: 

server:
  port: 8050
