spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xingmeichen/helper
          searchPaths: spring-cloud-in-action/config-repository
          username: xingmeichen
          password: ${password}
          label: master
      discovery:
        enabled: true

server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true