spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helper
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

ribbon:
  ConnectionTimeout: 60000
  ReadTimeout: 60000
  eureka:
    enabled: true


mybatis:
  configLcation: classpath:mybatis.xml
  type-aliases-package: com.mabel.pojo
  mapperLacation: classpath:mapper