spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helper
    username: root
    password: 20190228
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user

server:
  port: 8040

eureka:
  client:
    serviceUrl:
      # defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/
      defaultZone: http://localhost:8010/eureka/


ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true


mybatis:
  configLcation: classpath:mybatis.xml
  type-aliases-package: com.mabel.pojo
  mapperLacation: classpath:mapper