spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helper
    username: helper_admin
    password: 20220419
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 30
        min-idle: 0

server:
  port: 8040

eureka:
  client:
    serviceUrl:
      # defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/
      defaultZone: http://localhost:8010/eureka/

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true

mybatis:
  configLcation: classpath:mybatis.xml
  type-aliases-package: com.mabel.pojo
  mapperLacation: classpath:mapper