spring:
  application:
    name: api-gateway

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/

#swagger:
#  base-package: com.mabel.controller

#zuul:
#  routes:
#    user:
#      url: http://localhost:8081

zuul:
  set-content-length: true
#  ignoredServices: "*"   # 表示允许所有请求直接转发，不需要通过任何验证
  routes:
    registry:
      path: /registry/**
      url: http://localhost:8010
    user:
      path: /user/**
      serviceId: user  # serviceId 也可以用url代替
    admin:
      path: /admin/**
      serviceId: admin

  max:
    host:
      connection: 200
      socket-timeout-millis: 6000
      connect-timeout-millis: 6000

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true

#ribbon:
#  eureka:
#    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000