spring:
  application:
    name: api-gateway

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#swagger:
#  base-package: com.mabel.controller

#zuul:
#  routes:
#    user:
#      url: http://localhost:8081

zuul:
  set-content-length: true
#  ignoredServices: "*"   # 表示允许所有请求直接转发，不需要通过任何验证
  routes:
    registry:
      path: /registry/**
      url: http://localhost:8080
    user:
      path: /user/**
      serviceId: user  # serviceId 也可以用url代替
    admin:
      path: /admin/**
      serviceId: admin

  max:
    host:
      connection: 200
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000

ribbon:
  Connectiontimeout: 150000
  Readtimeout: 150000
  eureka:
    enabled: true

#ribbon:
#  eureka:
#    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 150000