spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helper
    username: helper_admin
    password: 20220419
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: admin

server:
  port: 8030

eureka:
  client:
    serviceUrl:
      ##defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/
      defaultZone: http://registry-dev:8010/eureka/

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true

mybatis:
  configLcation: classpath:mybatis.xml
  type-aliases-package: com.mabel.pojo
  mapperLacation: classpath:mapper