spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helper
    username: root
    password: 20190228
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: admin

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

ribbon:
  Connectiontimeout: 60000
  Readtimeout: 60000
  eureka:
    enabled: true
#ribbon:
#  eureka:
#    enabled: true

mybatis:
  configLcation: classpath:mybatis.xml
  type-aliases-package: com.mabel.pojo
  mapperLacation: classpath:mapper