spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/helper
#    username: root
#    password: 20190228
#    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: registry

server:
  port: 8010

eureka:
  enableSelfPreservation: false
  instance:
    hostname: registry-dev

  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      # 配置多节点的注册中心，注意这里必须使用属性配置的主机名 eureka,而不能用localhost, 且需要配置host,
      # defaultZone: http://registry-dev-peer1:8011/eureka/, http://registry-dev-peer2:8012/eureka/
      defaultZone: http://localhost:${server.port}/eureka/

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true

management:
  security:
    enable: false