spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/helper
  #    username: root
  #    password: 20190228
  #    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: registry

server:
  port: 8012

eureka:
  enableSelfPreservation: false
  instance:
    hostname: registry-dev-peer2

  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://registry-dev:8010/eureka/, http://registry-dev-peer1:8011/eureka/

ribbon:
  ConnectionTimeout: 6000
  ReadTimeout: 6000
  eureka:
    enabled: true